= Task3: Writing Byteman rule and helper usage

== Goal

* <<part1>>: write a Byteman rule on your own
* <<part2>>: write a Byteman rule on your own - tuning
* <<part3>>: how to get running your own helper class

IMPORTANT: Expecting you won't change the *java* code!


[[task3-setup]]
== Setup

. setup your environment (link:../README.adoc[prerequisites])
. go to the directory `$BYTEMAN_WORKSHOP/task3`: `cd "$BYTEMAN_WORKSHOP/task3"`
. compile java sources: `mvn clean install`
. you can import the projects from folders `greetings` and `helper` to you IDE

[[part1]]
== Part1: write a Byteman rule

=== Task

* write one Byteman rule which changes behaviour of `Task3GreetingsProcessor1`
  and `Task3GreetingsProcessor2` to changes return values when
  greetings words *hello* or *hi* are passed to them as parameters
* try to use only one Byteman rule to do the work!

When you run the prepared java program with parameters `hello hi` you will get output
```
output: [#1:hello] [#2:abstract:hi]
```

the Byteman rule should change the behaviour when used with the same parameters to get
```
output: [#1:god bless you] [#2:abstract:god bless you]
```

if the Byteman rule is applied and you run with other parameters e.g. `hola ola` the Byteman rule does not change
the behaviour of the program
```
output: [#1:hola] [#2:abstract:ola]
```

=== Hints

* go to the directory `$BYTEMAN_WORKSHOP/task3/greetings` and observe sources `$BYTEMAN_WORKSHOP/task3/greetings/src/main/java`
* run the program to see the output
  .. `cd $BYTEMAN_WORKSHOP/task3/greetings`
  .. `java -cp target/byteman-workshop-task3-greetings-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task3Main hello hi`
* you can observe there is an interface and implementations
* Byteman DSL skeleton is
```
RULE ...
CLASS <or> INTERFACE ...
METHOD ...
AT ...
IF ...
DO ...
ENDRULE
```
* if you want to use only one rule to get the work done, check inspiration at
  http://downloads.jboss.org/byteman/4.0.0/byteman-programmers-guide.html#overriding-interface-rules
* you can check content of the method parameters `$1`, `$2`, ... in the `IF` clause, see
  http://downloads.jboss.org/byteman/4.0.0/byteman-programmers-guide.html#rule-bindings-and-parameterization
* you can even redefine the method parameters `$1`, `$2`, ... in the `DO` clause, see
* you can use the empty `task3.btm` file to write the Byteman rule into and run then
** `java -javaagent:$BYTEMAN_JAR=script:./task3.btm -cp target/byteman-workshop-task3-greetings-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task3Main hello hi`
* you can check the syntax of the `btm` file with `bmcheck` tool
** `$BYTEMAN_HOME/bin/bmcheck.sh -p org.jboss.btm.workshop -cp target/byteman-workshop-task3-greetings-1.0.0-SNAPSHOT.jar task3.btm`
* you can get verbose/debug messages from byteman processing when you use
** `java -javaagent:$BYTEMAN_JAR=script:./task3.btm -cp target/byteman-workshop-task3-greetings-1.0.0-SNAPSHOT.jar -Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.debug org.jboss.btm.workshop.Task3Main hello hi`

=== Solution

Possible solution script is

```
RULE change message when it's greeting
INTERFACE ^Task3GreetingsProcessor
METHOD process
AT ENTRY
IF $1.contains("hello") || $1.contains("hi")
DO
  $1 = "god bless you"
ENDRULE
```

* for influence all the child classes you need to use the `ITERFACE` with sign `^`
  for rule being propagated down through the abstract class
* the `$1` says the first parameter passed to the method `process` of interface `Task3GreetingsProcessor`
* you can check in `IF` the method parameter and at the same time you can change its value


[[part2]]
== Part2: write a Byteman rule : get rid of word 'abstract' in the output _(Optional)_



== Notes

NOTE: you can use Byteman argument `org.jboss.byteman.dump.generated.classes`
      to get dumped bytecode of classes changed by Byteman rules

=== Errors

[[could-not-load-class]]
```
$ $BYTEMAN_HOME/bin/bmcheck.sh "$BYTEMAN_WORKSHOP/task2/task2.btm"
Checking rule message handling against class java.io.PrintStream
Parsed rule "message handling" for class java.io.PrintStream
Type checked rule "message handling"

ERROR : Could not load class Task2HelloWorld declared in rule "message handling" loaded from /home/ochaloup/presentations/byteman-workshop/task2/task2.btm line 14
TestScript: 1 total errors
            0 total warnings
            0 parse errors
            0 type errors
            0 type warnings
```

[[rule-syntax-error]]
```
$ $BYTEMAN_HOME/bin/bmcheck.sh -p org.jboss.btm.workshop -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar ./task2.btm
Checking rule message handling against class java.io.PrintStream
ERROR : Failed to parse rule "message handling" loaded from ./task2.btm line 4
org.jboss.byteman.rule.exception.ParseException: rule message handling
./task2.btm line 4 : unable to recover from previous errors

Checking rule message handling against class org.jboss.btm.workshop.Task2HelloWorld
Parsed rule "message handling" for class org.jboss.btm.workshop.Task2HelloWorld
Type checked rule "message handling"

TestScript: 1 total errors
           0 total warnings
           1 parse errors
           0 type errors
           0 type warnings
```

[[duplicate-rule-name]]
```
java -javaagent:$BYTEMAN_JAR=script:./task2.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.jboss.byteman.agent.Main.premain(Main.java:274)
        ... 6 more
Caused by: java.lang.Exception: Transformer : duplicate script name message handlingin file ./task2.btm  line 15
 previously defined in file ./task2.btm  line 6
        at org.jboss.byteman.agent.Transformer.<init>(Transformer.java:92)
        ... 11 more
FATAL ERROR in native method: processing of -javaagent failed
Aborted (core dumped)
```

[[java-lang-class-error]]
```
java -javaagent:$BYTEMAN_JAR=script:./task2.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/byteman/rule/exception/EarlyReturnException
        at java.io.PrintStream.println(PrintStream.java)
        at org.jboss.byteman.rule.helper.Helper.dotraceln(Helper.java:437)
        at org.jboss.byteman.rule.helper.Helper.err(Helper.java:220)
        at org.jboss.byteman.rule.Rule.execute(Rule.java:826)
        at org.jboss.byteman.rule.Rule.execute(Rule.java:767)
        at org.jboss.btm.workshop.Task2HelloWorld.main(Task2HelloWorld.java:14)
```

[[debug-verbose-outcome]]
```
java -javaagent:$BYTEMAN_JAR=script:./task2.btm,boot:$BYTEMAN_JAR -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar -Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.debug=true org.jboss.btm.workshop.Task2HelloWorld
AccessManager:init Initialising default AccessManager
retransforming java.io.PrintStream
org.jboss.byteman.agent.Transformer : possible trigger for rule message handling in class java.io.PrintStream
RuleTriggerMethodAdapter.injectTriggerPoint : inserting trigger into java.io.PrintStream.println(java.lang.String) void for rule message handling
org.jboss.byteman.agent.Transformer : inserted trigger for message handling in class java.io.PrintStream
org.jboss.byteman.agent.Transformer : possible trigger for rule print info message in class org.jboss.btm.workshop.Task2HelloWorld
RuleTriggerMethodAdapter.injectTriggerPoint : inserting trigger into org.jboss.btm.workshop.Task2HelloWorld.main(java.lang.String[]) void for rule print info message
org.jboss.byteman.agent.Transformer : inserted trigger for print info message in class org.jboss.btm.workshop.Task2HelloWorld
Rule.execute called for print info message_1
HelperManager.install for helper class org.jboss.byteman.rule.helper.Helper
calling activated() for helper class org.jboss.byteman.rule.helper.Helper
Default helper activated
calling installed(print info message) for helper classorg.jboss.byteman.rule.helper.Helper
Installed rule using default helper : print info message
print info message execute
Rule.execute called for message handling_0
HelperManager.install for helper class org.jboss.byteman.rule.helper.Helper
calling installed(message handling) for helper classorg.jboss.byteman.rule.helper.Helper
Installed rule using default helper : message handling
message handling execute
Hello Byteman! : Task2
Rule.execute called for message handling_0
message handling execute
Hello Byteman! : Task2
```

[[java-lang-class-error2]]
```
$ java -javaagent:$BYTEMAN_JAR=script:./task2.string.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar -Dorg.jboss.byteman.transform.all org.jboss.btm.workshop.Task2HelloWorld
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/byteman/rule/exception/EarlyReturnException
    at java.lang.String.<init>(String.java:152)
    at org.jboss.btm.workshop.Task2HelloWorld.main(Task2HelloWorld.java:14)
```
