= Task2: Discovering issues in Byteman script

== Goal

* <<part1>>: to know tooling to verify correctness of the Byteman script
* <<part2>>: to know how to see debug info from Byteman workload
* <<part3>>: to know how to inject new behaviour to `java.lang` classes

=== Rules

IMPORTANT: Do not change the *java* code!

Imagine you need to change the program behaviour but you can't change the sources.
Your expected solution is changing rules in the Byteman script.

[[task2-setup]]
== Setup

. setup your environment (link:../README.adoc[prerequisites])
. go to the directory `$BYTEMAN_WORKSHOP/task2`: `cd "$BYTEMAN_WORKSHOP/task2"`
. compile java sources: `mvn clean install`
. check source code of `Task2HelloWorld.java` class
  ** you can go to directory `$BYTEMAN_WORKSHOP/task2/src/main/java/org/jboss/btm/workshop`
  ** you can import the code as maven project under you IDE


[[part1]]
== Part1: use Byteman script to check script correctness

=== Task

* Use Byteman tooling to see what are errors in the script `task2.btm` (hint: `bmcheck.(sh|bat)`)
* Correct the `task2.btm` for getting *no* syntax errors when running `bmcheck`

=== References

see Byteman programmer's guide section section
http://downloads.jboss.org/byteman/4.0.0/byteman-programmers-guide.html#checking-rules-offline-using-script-bmcheck[Checking Rules Offline Using Script bmcheck]

=== Solution

. `cd "$BYTEMAN_WORKSHOP/task2"`
. run the tool `bmcheck` to verify errors in the Byteman script
  ** `$BYTEMAN_HOME/bin/bmcheck.sh "$BYTEMAN_WORKSHOP/task2/task2.btm"`
  ** you will get information that class `Task2HelloWorld` which is part of the Byteman script
     is not possible to load <<could-not-load-class>>.
     That means `bmcheck` does not see that class on the classpath which is needed for further verification.
  .. check content of the Byteman script `$BYTEMAN_WORKSHOP/task2/task2.btm`
. run the tool `bmcheck` when providing `Task2HelloWorld` to its classpath
  ** `$BYTEMAN_HOME/bin/bmcheck.sh -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar ./task2.btm`
  ** we provided the jar file with the `Task2HelloWorld` at the classpath but we still can see
   error of not  possible to load the class <<could-not-load-class>>.
   The reason is that the `Task2HelloWorld` is not defined in Byteman rule at `task2.btm`
   with fully qualified name. You can change the rule to add `org.jboss.btm.workshop`
   package before the class name. Or you can use `bmcheck` command line option.
. run the tool `bmcheck` with `Task2HelloWorld` at classpath and defining default
  package name where to search for not found classes
  ** `$BYTEMAN_HOME/bin/bmcheck.sh -p org.jboss.btm.workshop -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar ./task2.btm`
  ** you will see syntax error `org.jboss.byteman.rule.exception.ParseException` <<rule-syntax-error>>
  ** there is wrong syntax in the first rule. Byteman DSL does not understand `AT ENTER`.
   Change the line (line numer 4) to be `AT ENTRY`.
. run the `bmcheck` and see no errors now (`TestScript: no errors`)


[[part2]]
== Part2: start program without errors and get info about loaded rules

=== Goal

* Start the task2 `Task1HelloWorld` with Byteman agent and `task2.btm`
  and manage to start it without any errors
* To get verified rules Byteman loads and how it process them (hint: ask Byteman to show logs, `-Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.debug`)

=== Solution

. `cd "$BYTEMAN_WORKSHOP/task2"`
. when sources are compiled <<task2-setup>> then run the program with Byteman agent
  ** `java -javaagent:$BYTEMAN_JAR=script:./task2.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld`
  ** you will see there is a trouble in rule naming <<duplicate-rule-name>>
  ** observe content of the Byteman script `vim ./task2.btm`
. change the second rule name to something different (e.g. from `RULE  message handling` to `RULE  print info message`)
  ** now you will get a bit cryptic error that `java.io.PrintStream` is not found <<java-lang-class-error>>.
. the reason is that Byteman does not see the java runtime (`rt`) classes and
  you need to redefine Byteman to be loaded by boot classloader. There are two options
  using java standard command line attribute to add Byteman jar to the boot classpath `-Xbootclasspath/p:$BYTEMAN_JAR`
  or use the Byteman agent option `,boot:$BYTEMAN_JAR`.
  ** `java -javaagent:$BYTEMAN_JAR=script:./task2.btm,boot:$BYTEMAN_JAR -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld`
  ** now you can see the Byteman changed the behaviour of the program but strangely there
     is printed message `Hello Byteman! : Task2` twice. How is that?
. use the Byteman arguments to get Byteman verbose and get printed debug messages by use of `-Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.debug`
  ** `java -javaagent:$BYTEMAN_JAR=script:./task2.btm,boot:$BYTEMAN_JAR -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar -Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.debug org.jboss.btm.workshop.Task2HelloWorld`
  ** there is now quite a lot information printed <<debug-verbose-outcome>>.
     But from the console you can see there was invoked rule `print info message` from that follows `message handling`
     and again `message handling`. If you look at the `task2.btm` you can realize that
     the second rule (`print info message`) uses `java.io.PrintStream#println` to print
     information about execution to the console. That causes the first rule is invoked and changes
     the behaviour of the first rule.
. change the second rule `print info message` `DO` action to not using `#println` which triggers first rule.
  ** change from `System.out.println("Parameter one is: " + $@[1])` to `System.out.print("Parameter one is: " + $@[1] + "\n")`
. run the fixed script
  ** `java -javaagent:$BYTEMAN_JAR=script:./task2.btm,boot:$BYTEMAN_JAR -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld`


[[part3]]
== Part3: change behaviour of `java.lang` classes  _(Optional)_

=== Goal

* get running the `Task2HelloWorld` with Byteman script `task2.string.btm`

=== Solution

. `cd "$BYTEMAN_WORKSHOP/task2"`
. when sources are compiled <<task2-setup>> then run the program with Byteman agent
  ** `java -javaagent:$BYTEMAN_JAR=script:./task2.string.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld`
  ** you can see the script makes no change in the behaviour
  ** observe the content of the script file `vim task2.string.btm`
  ** the reason is that Byteman is not permitted to inject anything under `java.lang` classes.
  This is done from security reasons.
. add Byteman parameter `org.jboss.byteman.transform.all` to allow Byteman to inject changes to java core classes
  `java -javaagent:$BYTEMAN_JAR=script:./task2.string.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar -Dorg.jboss.byteman.transform.all org.jboss.btm.workshop.Task2HelloWorld`
  ** now you get the well-known `EarlyReturnException` <<java-lang-class-error2>>
. run with Byteman jar loaded by boot class loader
  ** `java -javaagent:$BYTEMAN_JAR=script:./task2.string.btm,boot:$BYTEMAN_JAR -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar -Dorg.jboss.byteman.transform.all org.jboss.btm.workshop.Task2HelloWorld`
. you can run with debug enabled now too
  ** `java -javaagent:$BYTEMAN_JAR=script:./task2.string.btm,boot:$BYTEMAN_JAR -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.debug org.jboss.btm.workshop.Task2HelloWorld`


== Notes

NOTE: you can use Byteman argument `org.jboss.byteman.dump.generated.classes`
      to get dumped bytecode of classes changed by Byteman rules

[WARNING]
====
if you create a rule which has some syntax error it's not true that you get error
during program execution. You will see errors when you switch on the `debug`
or when you use the `bmcheck` tool.

By interest you can try to create a rule where in the `DO` clause you define
two actions not delimited with comma (`,`) or semicolon (`;`)

```
DO
  System.out.print("Hello ")
  System.out.println("world!")
```

when you run it fails but there will be errors shown only when you run with debug
otherwise syntax error is hidden by Byteman, see error <<do-action-parse-error>>.
====

[NOTE]
====
If you want to throw an exception from the rule you won't be permitted
if you are throwing checked exception and the method does not throw such one. <<checked-exception-failure>>
Try this where `java.io.IOException` is thrown.

```
java -javaagent:$BYTEMAN_JAR=script:./task2.exception.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld
```

If you try to throw unchecked exception then you are free to do so and
Byteman will permits to do so.
====

=== Errors

[[could-not-load-class]]
```
$ $BYTEMAN_HOME/bin/bmcheck.sh "$BYTEMAN_WORKSHOP/task2/task2.btm"
Checking rule message handling against class java.io.PrintStream
Parsed rule "message handling" for class java.io.PrintStream
Type checked rule "message handling"

ERROR : Could not load class Task2HelloWorld declared in rule "message handling" loaded from /home/ochaloup/presentations/byteman-workshop/task2/task2.btm line 14
TestScript: 1 total errors
            0 total warnings
            0 parse errors
            0 type errors
            0 type warnings
```

[[rule-syntax-error]]
```
$ $BYTEMAN_HOME/bin/bmcheck.sh -p org.jboss.btm.workshop -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar ./task2.btm
Checking rule message handling against class java.io.PrintStream
ERROR : Failed to parse rule "message handling" loaded from ./task2.btm line 4
org.jboss.byteman.rule.exception.ParseException: rule message handling
./task2.btm line 4 : unable to recover from previous errors

Checking rule message handling against class org.jboss.btm.workshop.Task2HelloWorld
Parsed rule "message handling" for class org.jboss.btm.workshop.Task2HelloWorld
Type checked rule "message handling"

TestScript: 1 total errors
           0 total warnings
           1 parse errors
           0 type errors
           0 type warnings
```

[[duplicate-rule-name]]
```
java -javaagent:$BYTEMAN_JAR=script:./task2.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.jboss.byteman.agent.Main.premain(Main.java:274)
        ... 6 more
Caused by: java.lang.Exception: Transformer : duplicate script name message handlingin file ./task2.btm  line 15
 previously defined in file ./task2.btm  line 6
        at org.jboss.byteman.agent.Transformer.<init>(Transformer.java:92)
        ... 11 more
FATAL ERROR in native method: processing of -javaagent failed
Aborted (core dumped)
```

[[java-lang-class-error]]
```
java -javaagent:$BYTEMAN_JAR=script:./task2.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/byteman/rule/exception/EarlyReturnException
        at java.io.PrintStream.println(PrintStream.java)
        at org.jboss.byteman.rule.helper.Helper.dotraceln(Helper.java:437)
        at org.jboss.byteman.rule.helper.Helper.err(Helper.java:220)
        at org.jboss.byteman.rule.Rule.execute(Rule.java:826)
        at org.jboss.byteman.rule.Rule.execute(Rule.java:767)
        at org.jboss.btm.workshop.Task2HelloWorld.main(Task2HelloWorld.java:14)
```

[[debug-verbose-outcome]]
```
java -javaagent:$BYTEMAN_JAR=script:./task2.btm,boot:$BYTEMAN_JAR -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar -Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.debug=true org.jboss.btm.workshop.Task2HelloWorld
AccessManager:init Initialising default AccessManager
retransforming java.io.PrintStream
org.jboss.byteman.agent.Transformer : possible trigger for rule message handling in class java.io.PrintStream
RuleTriggerMethodAdapter.injectTriggerPoint : inserting trigger into java.io.PrintStream.println(java.lang.String) void for rule message handling
org.jboss.byteman.agent.Transformer : inserted trigger for message handling in class java.io.PrintStream
org.jboss.byteman.agent.Transformer : possible trigger for rule print info message in class org.jboss.btm.workshop.Task2HelloWorld
RuleTriggerMethodAdapter.injectTriggerPoint : inserting trigger into org.jboss.btm.workshop.Task2HelloWorld.main(java.lang.String[]) void for rule print info message
org.jboss.byteman.agent.Transformer : inserted trigger for print info message in class org.jboss.btm.workshop.Task2HelloWorld
Rule.execute called for print info message_1
HelperManager.install for helper class org.jboss.byteman.rule.helper.Helper
calling activated() for helper class org.jboss.byteman.rule.helper.Helper
Default helper activated
calling installed(print info message) for helper classorg.jboss.byteman.rule.helper.Helper
Installed rule using default helper : print info message
print info message execute
Rule.execute called for message handling_0
HelperManager.install for helper class org.jboss.byteman.rule.helper.Helper
calling installed(message handling) for helper classorg.jboss.byteman.rule.helper.Helper
Installed rule using default helper : message handling
message handling execute
Hello Byteman! : Task2
Rule.execute called for message handling_0
message handling execute
Hello Byteman! : Task2
```

[[java-lang-class-error2]]
```
$ java -javaagent:$BYTEMAN_JAR=script:./task2.string.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar -Dorg.jboss.byteman.transform.all org.jboss.btm.workshop.Task2HelloWorld
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/byteman/rule/exception/EarlyReturnException
    at java.lang.String.<init>(String.java:152)
    at org.jboss.btm.workshop.Task2HelloWorld.main(Task2HelloWorld.java:14)
```

[[do-action-parse-error]]
```
org.jboss.byteman.agent.Transformer : error parsing rule print info message
org.jboss.byteman.rule.exception.ParseException: rule print info message
./task2.btm line 19 : invalid expression
./task2.btm : unable to recover from previous errors
org.jboss.byteman.rule.exception.ParseException: rule print info message
./task2.btm line 19 : invalid expression
./task2.btm : unable to recover from previous errors
    at org.jboss.byteman.rule.Rule.<init>(Rule.java:229)
    at org.jboss.byteman.rule.Rule.create(Rule.java:381)
    at org.jboss.byteman.agent.TransformContext.parseRule(TransformContext.java:178)
    at org.jboss.byteman.agent.TransformContext.transform(TransformContext.java:88)
    at org.jboss.byteman.agent.Transformer.transform(Transformer.java:745)
    at org.jboss.byteman.agent.Transformer.tryTransform(Transformer.java:812)
    at org.jboss.byteman.agent.Transformer.tryTransform(Transformer.java:784)
    at org.jboss.byteman.agent.Transformer.transform(Transformer.java:262)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

[[checked-exception-failure]]
```
$ java -javaagent:$BYTEMAN_JAR=script:./task2.exception.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld
Rule.ensureTypeCheckedCompiled : error type checking rule throw exception
org.jboss.byteman.rule.exception.TypeException: ThrowExpression.typeCheck : exception type not declared by trigger method java.io.IOException file ./task2.exception.btm line 8
    at org.jboss.byteman.rule.expression.ThrowExpression.checkThrownTypeIsValid(ThrowExpression.java:426)
    at org.jboss.byteman.rule.expression.ThrowExpression.typeCheck(ThrowExpression.java:175)
    at org.jboss.byteman.rule.Action.typeCheck(Action.java:106)
    at org.jboss.byteman.rule.Rule.typeCheck(Rule.java:581)
    at org.jboss.byteman.rule.Rule.ensureTypeCheckedCompiled(Rule.java:513)
    at org.jboss.byteman.rule.Rule.execute(Rule.java:786)
    at org.jboss.byteman.rule.Rule.execute(Rule.java:767)
    at org.jboss.btm.workshop.Task2HelloWorld.main(Task2HelloWorld.java)
```
