= Task2: Discovering issues in Byteman script

== Goal

* <<part1>>: to know tooling to verify correctness of the Byteman script

IMPORTANT: Expecting you won't change the *java* code!

== Source code overview

The directory `task2` contains one main java class `org.jboss.btm.workshop.Task2HelloWorld`

[[task2-setup]]
== Setup

. setup your environment at link:../README.adoc[prerequisites], ensures sources are compiled (`mvn install -DskipTests`)
. go to the directory `$BYTEMAN_WORKSHOP/task2`: `cd "$BYTEMAN_WORKSHOP/task2"`
. check source code of `Task2HelloWorld.java` class
  ** you can go to directory `$BYTEMAN_WORKSHOP/task2/src/main/java/org/jboss/btm/workshop`
  ** you can import the code as maven project under you IDE


[[part1]]
== Use Byteman script to check script correctness

=== Task

* Run java main class `Task2HelloWorld` 
* Use Byteman tooling to see what are errors in the script `task2.btm` (hint: `bmcheck.(sh|bat)`)
* Correct the `task2.btm` for getting *no* syntax errors when running `bmcheck`
** expected output of `bmcheck` is to see no errors (last line of printing): `TestScript: no errors`
* Run the program with the Byteman rule to observe message `<byteman trojan> : Hello world!`

=== References

see Byteman programmer's guide section section
http://downloads.jboss.org/byteman/4.0.0/byteman-programmers-guide.html#checking-rules-offline-using-script-bmcheck[Checking Rules Offline Using Script bmcheck]

=== Hints

* see the `bin` of Byteman installation to locate the `$BYTEMAN_HOME/bin/bmcheck.sh <scriptfile>`
* check the location specifier in documentation at http://downloads.jboss.org/byteman/4.0.0/byteman-programmers-guide.html#location-specifiers
* `bmcheck.sh` needs to understand classes which are in the script, you will need
  provide the compiled jar to the `bmcheck.sh` classpath (use parameter `-cp`)
* if `btm` script contains classes of not fully qualified name (only the class without package)
  the `bmcheck.sh` needs to  be informed what are packages to consider, that's done via parameter `-p`
  (the `Task2HelloWorld` is in the package `org.jboss.btm.workshop`)
* you can run the program when Byteman is not applied with this command
** `java -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld`
* the Byteman jar is at `$BYTEMAN_JAR`, the script to be applied is `./task2.btm`
* in case of troubles try to switch on Byteman debug parameters `-Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.debug`
* Byteman does not inject rules to package `java.lang` by default. To permit so you need to use argument `-Dorg.jboss.byteman.transform.all`
* for Byteman being to see (and put injection) the `java.lang` classes it needs to get loaded by boot classloader,
  for not observing `NoClassDefFoundError` <<boot-classloader>> use `boot:` parameter of the `-javaagent` with byteman jar
** `-javaagent=...,boot:$BYTEMAN_JAR`

NOTE: there is difference between `bmcheck` tooling and the Byteman agent. `bmcheck` script needs
      to know the fully qualified name of class (advices with `-p`) where Byteman agent
      is fine with just class name (without package) and will distinguish it

== Notes

NOTE: you can use Byteman argument `org.jboss.byteman.dump.generated.classes`
      to get dumped bytecode of classes changed by Byteman rules

[WARNING]
====
if you create a rule which has some syntax error it's not true that you get error
during program execution. You will see errors when you switch on the `debug`
or when you use the `bmcheck` tool.

By interest you can try to create a rule where in the `DO` clause you define
two actions not delimited with comma (`,`) or semicolon (`;`)

```
DO
  System.out.print("Hello ")
  System.out.println("world!")
```

when you run it fails but there will be errors shown only when you run with debug
otherwise syntax error is hidden by Byteman, see error <<do-action-parse-error>>.
====

[NOTE]
====
If you want to throw an exception from the rule you won't be permitted
if you are throwing checked exception and the method does not throw such one. <<checked-exception-failure>>
Try this where `java.io.IOException` is thrown.

```
java -javaagent:$BYTEMAN_JAR=script:./task2.exception.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld
```

If you try to throw unchecked exception then you are free to do so and
Byteman will permits to do so.
====

=== Errors

[[boot-classloader]]
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/byteman/rule/exception/EarlyReturnException
  at java.lang.String.<init>(String.java:152)
  at org.jboss.btm.workshop.Task2HelloWorld.main(Task2HelloWorld.java:14)
```

[[rule-syntax-error]]
```
$ $BYTEMAN_HOME/bin/bmcheck.sh -p org.jboss.btm.workshop -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar ./task2.btm
Checking rule message handling against class java.io.PrintStream
ERROR : Failed to parse rule "message handling" loaded from ./task2.btm line 4
org.jboss.byteman.rule.exception.ParseException: rule message handling
./task2.btm line 4 : unable to recover from previous errors

Checking rule message handling against class org.jboss.btm.workshop.Task2HelloWorld
Parsed rule "message handling" for class org.jboss.btm.workshop.Task2HelloWorld
Type checked rule "message handling"

TestScript: 1 total errors
           0 total warnings
           1 parse errors
           0 type errors
           0 type warnings
```

[[name-duplication]]
```
java -javaagent:$BYTEMAN_JAR=script:./task2.btm -cp target/byteman-workshop-task2-1.0.0-SNAPSHOT.jar org.jboss.btm.workshop.Task2HelloWorld
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.jboss.byteman.agent.Main.premain(Main.java:274)
        ... 6 more
Caused by: java.lang.Exception: Transformer : duplicate script name make byteman to workin file ./task2.btm  line 20
 previously defined in file ./task2.btm  line 6
        at org.jboss.byteman.agent.Transformer.<init>(Transformer.java:92)
        ... 11 more
FATAL ERROR in native method: processing of -javaagent failed
Aborted (core dumped)
```
